# config/sphinx.yml
development:
  port: 9312
  searchd_file_path: "db/sphinx"
  ignore_chars: "., U+002E"
test:
  port: 9312
  searchd_file_path: "db/sphinx"
  ignore_chars: "., U+002E"
production:
  port: 9312
  searchd_file_path: "db/sphinx"
  ignore_chars: "., U+002E"